server:
  port: 8087
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/MakeMyYatraa
  application:
    name: hotel-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true